project_id = "global-ethnography"

[api]
enabled = true
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]

[db]
major_version = 15

[auth]
enabled = true
enable_signup = false

[storage]
enabled = true
file_size_limit = "5MiB"
